### ISSUE TITLE
Printing spec symbols like Æ, Ø, and Å on TSP700II

### ISSUE THREAD

**Issue by OlyaMonka** [star-micronics/StarXpand-SDK-iOS#6]
## Description
Tried to use StarXpandSDK example, with spec symbols.

## Your device where the bug occurs 
 - Device: 
    *iPad*
 - OS:
    *iOS 15.0*

## Your printer
- Model Names:
    *TSP650II*
- Interface:
    *Bluetooth*

## Additional context

Changed sample code with using .styleInternationalCharacter(.norway)
```
let builder = StarXpandCommand.StarXpandCommandBuilder()
        _ = builder.addDocument(StarXpandCommand.DocumentBuilder.init()
                                    .addPrinter(StarXpandCommand.PrinterBuilder()
                                                    .actionPrintImage(StarXpandCommand.Printer.ImageParameter(image: logo, width: 406))
                                                    .styleCharacterSpace(0)
                                                    .styleAlignment(.center)
                                                    .styleInternationalCharacter(.norway)
                                                    .actionPrintText("Søk etter bruker-ID\n" +
                                                                     "123 Star Road\n" +
                                                                     "City, State 12345\n" +
                                                                     "\n")
                                                    .styleAlignment(.left)
                                                    .actionPrintText("Date:MM/DD/YYYY    Time:HH:MM PM\n" +
                                                                     "--------------------------------\n" +
                                                                     "\n")
                                                    .add(
                                                        StarXpandCommand.PrinterBuilder()
                                                            .styleBold(true)
                                                            .actionPrintText("SALE \n")
                                                    )
                                                    .actionPrintText("SKU         Description    Total\n" +
                                                                     "300678566   PLAIN T-SHIRT  10.99\n" +
                                                                     "300692003   BLACK DENIM    29.99\n" +
                                                                     "300651148   BLUE DENIM     29.99\n" +
                                                                     "300642980   STRIPED DRESS  49.99\n" +
                                                                     "300638471   BLACK BOOTS    35.99\n" +
                                                                     "\n" +
                                                                     "Subtotal                  156.95\n" +
                                                                     "Tax                         0.00\n" +
                                                                     "--------------------------------\n")
                                                    .actionPrintText("Total     ")
                                                    .add(
                                                        StarXpandCommand.PrinterBuilder()
                                                            .styleMagnification(StarXpandCommand.MagnificationParameter(width: 2, height: 2))
                                                            .actionPrintText("   156.95 kr\n")
                                                    )
                                                    .actionPrintText("--------------------------------\n" +
                                                                     "\n" +
                                                                     "Charge\n" +
                                                                     "156.95\n" +
                                                                     "Visa XXXX-XXXX-XXXX-0123\n" +
                                                                     "\n")
                                                    .add(
                                                        StarXpandCommand.PrinterBuilder()
                                                            .styleInvert(true)
                                                            .actionPrintText("Refunds and Exchanges\n")
                                                    )
                                                    .actionPrintText("Within ")
                                                    .add(
                                                        StarXpandCommand.PrinterBuilder()
                                                            .styleUnderLine(true)
                                                            .actionPrintText("30 days")
                                                    )
                                                    .actionPrintText(" with receipt\n" +
                                                                     "And tags attached\n" +
                                                                     "\n")
                                                    .styleAlignment(.center)
                                                    .actionPrintBarcode(StarXpandCommand.Printer.BarcodeParameter(content: "0123456", symbology: .jan8)
                                                                            .setBarDots(3)
                                                                            .setHeight(5)
                                                                            .setPrintHRI(true))
                                                    .actionFeedLine(1)
                                                    .actionPrintQRCode(StarXpandCommand.Printer.QRCodeParameter(content: "Hello World.\n")
                                                                        .setLevel(.l)
                                                                        .setCellSize(8))
                                                    .actionCut(StarXpandCommand.Printer.CutType.partial)))
  ```                                            
        
but result isn't correct
![image](https://user-images.githubusercontent.com/1670651/194088865-9776bec2-acd9-4e3d-8350-7b22965d4a3b.png)

**Comment by OlyaMonka** [comment]
@bandit-ibayashi Any suggestions?

**Comment by j0mbajuice** [comment]
@OlyaMonka What firmware version do you have for the printer? You can print a self test from the printer to check this.

To print a self-test, turn the printer OFF, press and hold down the FEED button and then turn the printer back ON while holding the FEED button (release FEED once printing begins or when you hear the mechanical noise)

**Comment by OlyaMonka** [comment]
![image](https://user-images.githubusercontent.com/1670651/196495887-3c5ce5fd-9a5e-4a3c-9962-22537eaddb02.png)
@j0mbajuice please have a look

**Comment by xxkawspuffs** [comment]
@OlyaMonka Seems like a firmware upgrade may do the trick based on that print out. Assuming the printer is the 650II and not the 650IISK version you'd need to upgrade the firmware. Contact MST support and they should assist you with the upgrade. You can contact them here: support@starmicronics.com.

**Comment by xxkawspuffs** [comment]
@OlyaMonka Has this issue been fixed by doing a firmware upgrade to the printer?

**Comment by OlyaMonka** [comment]
@xxkawspuffs  No( Firmware was upgrade, but issue still exist. 
![image](https://user-images.githubusercontent.com/1670651/201335438-cb99c3f8-d0ec-472a-a98f-0633ea2f49fb.png)

**Comment by OlyaMonka** [comment]
@xxkawspuffs @j0mbajuice any suggestions?

**Comment by OlyaMonka** [comment]
Any updates?

**Comment by bandit-ibayashi** [comment]
@OlyaMonka We much appreciated your report and we are afraid our late response. We have confirmed this issue is reproducible.

We apologize for the inconvenience, but could you please try the following temporary workaround?

1. Download [StarIO](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/SDK/Pods/StarIO) and [StarIOExtension](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/tree/master/SDK/Pods/StarIO_Extension) framework and add these frameworks to your project.

   ![add_framework](https://user-images.githubusercontent.com/60959945/223940004-dd8c55b0-c144-4dfc-8a77-aeb5e0ca9d69.png)

2. Add "Objective-C Bridging Header" by following the steps below in order from the top to the bottom.
   * Select `File` - `New` - `File...` from Xcode menu.
   * Select `Header File`, and then click `Next`.
   * Enter a name and click `Create` to create an empty header file. In the example shown below, the header file name is "StarIO_Extension-Bridging-Header.h".
   * Write the following import lines in the header file created.
 
      ```
      #ifndef StarIO_Extension_Bridging_Header_h
      #define StarIO_Extension_Bridging_Header_h

      #import <StarIO/SMPortSwift.h>
      #import <StarIO_Extension/StarIoExt.h>

      #endif /* StarIO_Extension_Bridging_Header_h */
      ```
   * Specify the path to the created header file at Objective-C Bridging Header of Build Settings.

      ![specify-path](https://user-images.githubusercontent.com/60959945/223939848-17104b6e-3c39-4ca6-9583-d839418b7775.png)

3. Create print data using `StarIoExt.createCommandBuilder()`. 

   ``` swift
   let encoding = String.Encoding.windowsCP1252
        
   let extentionBuilder: ISCBBuilder = StarIoExt.createCommandBuilder(.starLine)
        
   extentionBuilder.beginDocument()
        
   extentionBuilder.append(SCBCodePageType.CP1252)
   extentionBuilder.append(SCBInternationalType.norway)
   extentionBuilder.appendCharacterSpace(0)
        
   extentionBuilder.appendAlignment(SCBAlignmentPosition.center)
   extentionBuilder.append(("Søk øetter bruker-ID\n").data(using: encoding))

   extentionBuilder.endDocument()
   ```

4. Use `StarXpandCommand.DocumentBuilder.addRaw()` method to add to `StarXpandCommandBuilder`.

   ```
   let builder = StarXpandCommand.StarXpandCommandBuilder()
   builder.addDocument(StarXpandCommand.DocumentBuilder.init()
         .addRaw(extentionBuilder.commands as Data))
   ``` 

We are sorry again to bother you, but thank you for your understanding.

**Comment by OlyaMonka** [comment]
@bandit-ibayashi 
Thanks for answer.
We used StarPRNT-SDK-iOS-Swift in previous version. But now we need to add TSP143IIIU USB POS printer for supporting, and this model is not included in that version of SDK, so we moved to StarXpand-SDK-iOS. How to fix a problem with spec symbols and support TSP143IIIU at the same time?

**Comment by gare-bear** [comment]
@OlyaMonka TSP143IIIU is supported in the StarPRNT SDK. Officially supported from StarIO 2.3.0 released in 2017.

**Comment by bandit-ibayashi** [comment]
@OlyaMonka Thank you for your confirmation.

As @gare-bear mentioned, our StarPRNT SDK has already been supported TSP143IIIU, but please note that the TSP143IIIU does not have printer built-in fonts as a printer specification and printing by text is not possible. It is needed to create raster data of receipt data on the host side like using `appendBitmap()` method on StarIO and so on to make it into a print command.

In this case, this symbol issue will not occur if the raster data can be created correctly on the host side.

**Comment by nickdnk** [comment]
@OlyaMonka Did you ever get this to work on the 650II?

**Comment by OlyaMonka** [comment]
@nickdnk No (

**Comment by OlyaMonka** [comment]
No, we did back to StarPRNT-SDK-iOS-Swift and  still use it.

**Comment by nickdnk** [comment]
> No, we did back to StarPRNT-SDK-iOS-Swift and still use it.

Okay. Pretty crazy that they won't fix this issue. I'll be trying the version 8 software soon and see how that works.

**Comment by KHosozawa** [comment]
@OlyaMonka 
@nickdnk 

Sorry for the long period without updates.

Regarding the TSP650II, printing these characters becomes possible by updating the firmware and **font data** to the latest versions. For firmware and font data updates, please contact the place of purchase.

Regarding the TSP700II, even with the latest firmware, printing these characters is not possible. We apologize, but for the TSP700II please use the method guided by bandit-ibayashi (https://github.com/star-micronics/StarXpand-SDK-iOS/issues/6#issuecomment-1461399995).
